### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by Megacrafter127** [vanautrui/vanautrui.org#67]
Missing closing parenthesis in line 41 of tools_logos_fragment.html.
`<span class="badge badge-light">Typescript (we do not want to use plain Javascript</span>`
should be
`<span class="badge badge-light">Typescript (we do not want to use plain Javascript)</span>`

**Comment by pointbazaar** [comment]
fixed in
7c19b92fdda6764d9edcfd1c58d600ddc00e414d
thank you for pointing it out :+1:
